figures:
  fig03_end2end_teacup:
    generator: end2end
    title: End-to-end invariance (Teacup)
    env: teacup
    method_a: CRTR
    method_b: ICM
    alpha: 1.0
    profile: rl

  fig06_convergence_teacup:
    generator: convergence
    title: Accelerated convergence (Teacup)
    env: teacup
    methods: [CRTR, ICM, RND, IDM, BISCUIT, CBM]
    alpha: 1.0
    profile: rl

  fig12_hparam_sweep_teacup:
    generator: hparam_sweep
    title: Hyperparameter sweep (Teacup)
    env: teacup
    method: CRTR
    profile: rl
